### ISSUE TITLE
Failing when used in conjunction with gen-files and mkdocstring plugin

### ISSUE THREAD

**Issue by madeinoz67** [onixpro/mkdocs-drawio-file#6]
when this plugin is used in conjunction with gen-files auto page generating plugin and mkdocstring, the plugin fails.

gen-files plugin is used to autogenerate doc pages for code reference documentation from the source, but doesn't create the .md files just the site files  

```
ERROR    -  mkdocstrings: No module named 'main<script type="text/javascript" src="https://viewer'
ERROR    -  Error reading page 'reference/main.md':
ERROR    -  Could not collect 'main<script type="text/javascript" src="https://viewer.diagrams.net/js/viewer-static.min.js"></script>'
```

A possible solution would be an option to ignore a doc path

e.g. "reference/" in this case

```
plugins:
 - drawio_file:
      exclude: 
         - reference/*
```

**Comment by pawamoy** [comment]
It looks like mkdocstrings finds a line like `::: main<script type="text/javascript" src="https://viewer` in your Markdown sources, and I'm not sure why. This plugin for DrawIO does not use this syntax, at least it's not mentioned in the README.
Looking at `::: main<script...`, is it possible that you're trying to reference a `main` package, and a newline is missing, concatenating the next `<script` thing?

**Comment by tuunit** [comment]
@pawamoy please try again with the latest release as it completely changes how the files are parsed.

**Comment by pawamoy** [comment]
I'll ask @madeinoz67 to try again instead: I'm just here to try and help :slightly_smiling_face:

**Comment by madeinoz67** [comment]
is now working many thanks.

I saw there was a version update when I updated my deps via poetry and came here to check :)

**Comment by tuunit** [comment]
I'm happy to hear that my changes fixes this issue as well :)
